# -*- coding: utf-8 -*-
"""hangman1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gZ9wmUZ1UhrdrMBlwS94Cq567PXwOudo
"""

import random
lives = 6

words=["pen", "book", "eraser"]
word_picked=random.choice(words)
print(word_picked)

display=[]

for letter in word_picked:
    display += "_"

    game_over=False

while not game_over and lives > 0:
  guessed_letter = input("Guess a Letter:")

  if guessed_letter not in word_picked:
    lives -= 1
    print("Incorrect guess, remaining lives:",lives)

  for index in range(len(word_picked)):
    letter = word_picked[index]
    if letter == guessed_letter:
      display[index] = guessed_letter
  print(display)

  if"_" not in display:
    game_over=True
    print("You win")

  if lives ==0:
    print("You Lose")