# -*- coding: utf-8 -*-
"""Hangman2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gHxhNzn1X9W6OjjgcNqJvJidRJbxEtOE
"""

import random

class Hangman:
    def __init__(self, words):

      #picking a random word
        self.word = random.choice(words).lower()

      #listing the letters of picked word
        self.word_letters = list(self.word)

      #keeping track of guesses taken
        self.used_letters = []
        self.lives = 6


    def game(self):
      #loop runs until the no. of lives and unguessed letters
        while self.word_letters and self.lives:

          #tracks lives remaining & guesses
            print(f"Lives: {self.lives}, Used words: {', '.join(self.used_letters)}")

            #displays letter if correct
            print(f"Word: {''.join(l if l in self.used_letters else '_' for l in self.word)}")

          #prompt
            guess = input("Guess a letter: ")

            #displays letter guessed
            if guess in self.used_letters:
                print("Already guessed.")
                continue

            self.used_letters.append(guess)
            if guess in self.word:
              while guess in self.word_letters:
                self.word_letters.remove(guess)

                print("Correct guess!")

            #reduces lives if wrong guess
            else:
                self.lives -= 1
                print("Wrong guess.")
        print(f"You {'won' if self.lives else 'lost'}")

words = ["hello", "world", "python"]

#instance
hangman_game = Hangman(words)

#game begining
hangman_game.game()

